env:
  browser: true
  commonjs: true
  es6: true
  jest: true
  phantomjs: true
  node: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 2017
  ecmaFeatures:
    jsx: true
  sourceType: module
rules:
  indent:
    - error
    - tab
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always
